# Generated by Django 5.2.7 on 2025-11-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('images', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('Urgente', 'Urgente'), ('Cultura', 'Cultura'), ('Saúde', 'Saúde'), ('Esporte', 'Esporte'), ('Educação', 'Educação')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
